### ISSUE TITLE
HA of supernode

### ISSUE THREAD

**Issue by happystefan** [alibaba/Dragonfly#232]
---
name: Question about Dragonfly
about: High available

---

## Question

Hi, 

IIUC, supernode is stateful and single point of failure. How to make supernode HA?

**Comment by pouchrobot** [comment]
Thanks for your contribution. 🍻 @happystefan 
While we thought **ISSUE TITLE** could be more specific, longer than 20 chars.
Please edit issue title instead of opening a new one.
More details, please refer to https://github.com/alibaba/pouch/blob/master/CONTRIBUTING.md

**Comment by happystefan** [comment]
> name: Question about Dragonfly
> about: High available
> ## Question
> 
> Hi,
> 
> IIUC, supernode is stateful and a single point of failure. How to make supernode HA?

**Comment by pouchrobot** [comment]
Thanks for your contribution. 🍻 @happystefan 
While we thought **ISSUE TITLE** could be more specific, longer than 20 chars.
Please edit issue title instead of opening a new one.
More details, please refer to https://github.com/alibaba/pouch/blob/master/CONTRIBUTING.md

**Comment by shenlanse** [comment]
@lowzj  This question also confuses me. I want deploy superNode into kubernetes with multi-replicas deployment, but superNode is stateful and they don't communicate with each other, so data is inconsistent.

So does it mean we have to deploy superNode in Standby mode.

**Comment by shenlanse** [comment]
Now  we deploy superNode with deployment in kubernetes. 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: supernode
  name: supernode
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: supernode
  template:
    metadata:
      labels:
        app: supernode
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
      - image: hub.c.163.com/hzlilanqing/supernode:0.3.0
        name: supernode
        ports:
        - containerPort: 8080
          hostPort: 8080
          name: tomcat
          protocol: TCP
        - containerPort: 8001
          hostPort: 8001
          name: register
          protocol: TCP
        - containerPort: 8002
          hostPort: 8002
          name: download
          protocol: TCP
        resources:
          requests:
            cpu: "2"
            memory: 4Gi
        volumeMounts:
        - mountPath: /etc/localtime
          name: ltime
        - mountPath: /home/admin/supernode/logs/
          name: log
        - mountPath: /home/admin/supernode/repo/
          name: data
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      tolerations:
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/master: ""
      volumes:
      - hostPath:
          path: /etc/localtime
          type: ""
        name: ltime
      - hostPath:
          path: /data/log/supernode
          type: ""
        name: log
      - hostPath:
          path: /data/supernode/repo/
          type: ""
        name: data
        
---

kind: Service
apiVersion: v1
metadata:
  name: supernode
  namespace: kube-system
spec:
  selector:
    app: supernode
  ports:
  - name: register
    protocol: TCP
    port: 8001
    targetPort: 8001
  - name: download
    protocol: TCP
    port: 8002
    targetPort: 8002
```
